[package]
name = "rust-chat-app-client"
version = "0.1.0"
authors = ["vapvin <vins@vins.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
